[tools]
node = "22"
chezmoi = "latest"
starship="latest"
awscli="latest"
kubectl="latest"
yarn="1"
uv="latest"
python="latest"

[tasks.prepare]
run = '''
    chmod +x ./starship.sh
    chmod +x ./fonts.sh
	brew install gnupg
'''

[tasks."podman:install"]
run='''
	brew install podman
	podman machine init
	podman machine start
'''

[tasks."podman:uninstall"]
run='''
	podman machine reset
	brew uninstall podman
'''

[tasks."fonts:install"]
run='./fonts.sh'

[tasks."starship:install"]
run='''
    brew install starship
    ./starship.sh
'''

[tasks."colima:install"]
run='~/.config/mise/colima.sh'

[tasks."colima:start"]
run='''
	colima start \
	--profile default \
	--activate \
	--arch aarch64 \
	--cpu 10 \
	--disk 100 \
	--memory 24 \
	--mount ${HOME}:w \
	--mount-inotify \
	--ssh-agent \
	--vm-type vz \
	--vz-rosetta \
	--verbose
'''